language: node_js
branches:
  only:
    - master
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_7cd0ff475ed3_key}" --iv "${encrypted_7cd0ff475ed3_iv}" --path-encrypted-key .travis_github_deploy_key.enc
  - $(npm bin)/update-branch --commands 'npm run build' --commit-message "Update gh-pages @ ${TRAVIS_COMMIT}" --directory 'dist' --distribution-branch 'gh-pages' --source-branch 'master'
env:
  global:
    - secure: "it76nM+rtWJC7g1ahjh3LBgWxDjauNI0n4iydIhsv/G7b8QLh5iC22KOpLPD7y2hxfJ/yxO3gxo3YMHW+JsimNh0EvPOcvKB/ltfuj7xBVoD/lOhE+XZfcpM0h6r5UnoU+o/T2avB7igAsy93TSt8sYrvl/9M3PYyQEHxJzTC60Z6T905gaQ5VP3TK9/63+fhmII4+a0H4ao8t1UtxBdfqAVoUznvlztL7YWVzlb7rBHXJhENxjpdweBypGkABpMLU/IiK132WlT+poQJDRUMC3G4nXLQvJgp5Vs5e5kYPBGByQxI9QkNIQT/UV6F7B2kOs+qSootaYAAaVlSxwwyGktxScqYU1ByCDrrBkhSUOWY51J+jqK37b6pwuHtrWqqfvT824M3l5Wc/nGC+1PP4NCgQv+dWFgAifRV4m+UtDiW3ELZJfn3P8B+5MPHhWQ3tEpvL50ymWYmcyWhnxQ0WbgIwZeYkhkSZ1s0fBzluV7bpQvacyo1cwAKAO1wZhGT1UUQfT5lI+o9XTOg0bneBPvZtYk2smI5omgcrYXGBYaAxdMb1Rwm6quiIBP681Czu147VdpzfhMBpIw872XjYthym0vzig7zQ1B3m/I453gHJ/LEPXdhubahycS3rv+SNphC5+zdDmU6kc4lbzzd17rSTNF2zaptTaZCUUIsQs="
